env:
  commonjs: true
  es2021: true
  node: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
rules: {
  "no-useless-constructor": 0,
  "no-undef": 0,
  "no-useless-escape": 0,
  "no-use-before-define": 0,
  "new-cap": 0
}
