on:
  release:
    types:
      - published
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Installing Node.js v16
        uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'
      - run: |
          git fetch origin main
          git checkout main
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Install ErelaJS
        run: yarn add erela.js
      - name: Compile source
        run: yarn compile
      - name: Remove ErelaJS
        run: yarn remove erela.js
      - name: Publish source
        run: |
          npm publish --access public || true
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_TOKEN }}'
