on:
  release:
    types:
      - published
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Installing Node.js v16
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'
      - run: |
          git fetch origin main
          git checkout main
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Compile source
        run: yarn compile
      - name: Publish source
        run: |
          npm publish --access public || true
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_TOKEN }}'
