name: CI
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
    - name: Installing Node.js v16
      uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3
      with:
          node-version: "16"
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
