name: CI
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
    - name: Installing Node.js v16
      uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3
      with:
          node-version: "16"
    - name: Install modules
      run: yarn
    - name: Install ErelaJS
      run: yarn add erela.js
    - name: Run tests
      run: yarn tests
